gallery/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.index, name='index'),

	url(r'^gallery_(?P<gallery_id>\d+)/$', views.gallery),
	url(r'^imgdetail_(?P<img_id>\d+)/$', views.img_detail),

	url(r'^thumb_(?P<img_id>\d+)_(?P<size>\d+).jpg$', views.img_thumbnail),

	url(r'^login/$', views.login_view, name='login'),
	url(r'^login_check/$', views.login_check),
	url(r'^verify_code/$', views.verify_code),

	url(r'^logout/$', views.logout_view),
	url(r'^register/$', views.register),
	url(r'^register_handle/$', views.register_handle),
	url(r'^username_check/$', views.username_check),
	url(r'^resetpwd/$', views.resetpwd),
	url(r'^resetpwd_handle/$', views.resetpwd_handle),
	url(r'^comment/(?P<gallery_id>\d+)/$', views.comment),
]

picview/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls', namespace='gallery')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

gallery/models.py
import os
import hashlib
import datetime
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from utils.base_model import AdvanceManager
from utils.get_bcrypt import get_bcrypt


class HighCategory(models.Model):
	"""大类
	"""
	name = models.CharField('大类名称', max_length=40, unique=True)
	order_by = models.IntegerField('排序', default=0)

	class Meta:
		verbose_name = verbose_name_plural = "大类"

	def __str__(self):
		return self.name


class Category(models.Model):
	"""分类
	"""
	high_cate = models.ForeignKey(HighCategory, verbose_name='大类', null=True)
	name = models.CharField('分类名称', max_length=40, unique=True)
	order_by = models.IntegerField('排序', default=0)

	class Meta:
		verbose_name = verbose_name_plural = "分类"

	def __str__(self):
		return '{} - {}'.format(self.high_cate, self.name)


class Gallery(models.Model):
	"""相册
	"""
	title = models.CharField('相册标题', max_length=40)

	# 相册可以属于多个分类
	category = models.ManyToManyField(Category, verbose_name='分类')

	owner = models.ForeignKey(User, verbose_name='创建人', null=True)
	order_by = models.IntegerField('排序', default=0)

	create_at = models.DateTimeField('创建时间', auto_now_add=True)
	modify_at = models.DateTimeField('最近修改时间', auto_now=True)

	objects = AdvanceManager()

	search_fields = ('title', 'category__name')

	class Meta:
		verbose_name = verbose_name_plural = "相册"

	def __str__(self):
		return self.title


class UploadImg(models.Model):
	"""上传图片表
	"""
	def get_file_path(instance, filename):
		now = datetime.datetime.now()
		directory_string_var = 'pics/{}/{}/'.format(now.year, now.month)
		return os.path.join(directory_string_var, filename)

	title = models.CharField('图片标题', max_length=40, null=True)
	gallery = models.ForeignKey(Gallery, verbose_name='所属相册')
	owner = models.ForeignKey(User, verbose_name='上传人', null=True)
	ext = models.CharField('文件类型', max_length=32, null=True, blank=True)
	md5 = models.CharField('MD5', max_length=32, null=True, blank=True)
	size = models.BigIntegerField('文件大小', null=True, blank=True)
	file = models.ImageField('图片文件', upload_to=get_file_path)
	order_by = models.IntegerField('排序', default=0)
	is_cover = models.BooleanField('是否相册封面', default=False)

	create_at = models.DateTimeField('创建时间', auto_now_add=True)
	modify_at = models.DateTimeField('修改时间', auto_now=True)

	class Meta:
		verbose_name = verbose_name_plural = "图片"

	def __str__(self):
		return str(self.file)

	def save(self, *args, **kwargs):
		# 计算文件大小和md5值
		md5 = hashlib.md5()
		size = 0
		for chunk in self.file.chunks():
			md5.update(chunk)
			size += len(chunk)
		self.md5 = md5.hexdigest()
		self.size = size
		# 记录扩展名
		self.ext = self.file.name.split('.')[-1].lower()
		super(UploadImg, self).save(*args, **kwargs)

		# 如果设为封面图，则同时取消同相册其他图片的is_cover属性
		if self.is_cover:
			UploadImg.objects.filter(gallery=self.gallery)\
					.exclude(id=self.id).update(is_cover=False)

	def get_url(self):
		"""获取图片url
		"""
		return "{}{}{}".format(settings.BASE_URL, settings.MEDIA_URL, self)
	
	def get_thumb_url(self, size=200):
		"""获取图片缩略图url
		"""
		return "{}/thumb_{}_200.jpg".format(settings.BASE_URL, self.id)
	
	def get_local_pathname(self):
		"""获取图片本地完整路径
		"""
		return os.path.join(settings.MEDIA_ROOT, str(self.file))


class PassportManager(models.Manager):
	"""Client的模型管理器类"""
	def add_one(self, username, password, phone, salt):
		# 添加一个普通用户
		obj = self.create(username=username,password=password,phone=phone,salt=salt)
		return obj

	def update_one(self, username, password, salt):
		obj = self.filter(username=username).update(password=password, salt=salt)
		return obj


class Client(models.Model):
	"""普通用户
	"""
	username = models.CharField(max_length=20, verbose_name='用户名')
	password = models.CharField(max_length=60, verbose_name='密码')
	phone = models.CharField(max_length=20, verbose_name='电话')
	salt = models.CharField(max_length=29, verbose_name='salt值')
	is_active = models.BooleanField(default=False, verbose_name='激活标志')

	objects = PassportManager()

	class Meta:
		verbose_name = verbose_name_plural = '用户'


class CommentManager(models.Manager):
	"""Comment的模型管理器类"""
	def add_one(self, author, gallery_id, content):
		obj = self.create(author_id=author, gallery_id=gallery_id, content=content)
		return obj


class Comment(models.Model):
	"""评论
	"""
	author = models.ForeignKey(Client, verbose_name='作者')
	gallery = models.ForeignKey(Gallery, verbose_name='评论相册', null=True)
	content = models.TextField('内容')

	create_at = models.DateTimeField('创建时间', auto_now_add=True)
	modify_at = models.DateTimeField('修改时间', auto_now=True)

	objects = CommentManager()

	class Meta:
		verbose_name = verbose_name_plural = "评论"

gallery/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from utils.thumbnail import Thumbnail
from utils.get_bcrypt import get_bcrypt
from gallery.models import HighCategory, Category, Gallery, UploadImg, Client, Comment
from django.views.decorators.http import require_GET,require_POST,require_http_methods
from django.core.urlresolvers import reverse

from PIL import Image, ImageDraw, ImageFont
from django.utils.six import BytesIO

from utils.decorators import login_required

import pprint


def index(request):
	"""首页
	"""
	# pprint.pprint(request.META['HTTP_USER_AGENT'])
	page_num = int(request.GET.get("page") or 1)
	cate_id = int(request.GET.get("sev") or 0)
	keywords = request.GET.get("q")

	data = {}
	# 大类
	data["high_cates"] = HighCategory.objects.all().order_by('order_by')

	# 首页展示相册分页
	gallery_qs = Gallery.objects.filter(
			id__in=UploadImg.objects.values('gallery')).order_by('-create_at')
	if cate_id:
		# 分类展示
		gallery_qs = gallery_qs.filter(category__id=cate_id)
	if keywords:
		# 搜索关键词
		gallery_qs = gallery_qs.search(keywords)

	# 分页器（每页数量为12）
	pager = Paginator(gallery_qs, 12)
	data["cur_page"] = pager.page(page_num)

	return render(request, 'index.html', data)


def img_thumbnail(request, img_id, size=200):
	"""返回图片缩略图
	"""
	try:
		img = UploadImg.objects.get(id=img_id)
	except UploadImg.DoesNotExist:
		raise Http404("Image does not exist")

	thumb_data = Thumbnail(
			image=img.get_local_pathname(), source_type='local',
			width=size, height=size, method='m')

	return HttpResponse(thumb_data, content_type="image/jpeg")


def gallery(request, gallery_id):
	try:
		gallery = Gallery.objects.get(pk=gallery_id)
	except Gallery.DoesNotExist:
		raise Http404("Gallery does not exist")
		
	comments = Comment.objects.filter(gallery=gallery).order_by('-create_at')
	
	# 分页器（每页数量为12）
	# pager = Paginator(comments, 3)
	# data["cur_page"] = pager.page()

	data = {
		"gallery": gallery,
		"comments": comments,
	}
	return render(request, 'gallery.html', data)


def img_detail(request, img_id):
	try:
		img = UploadImg.objects.get(pk=img_id)
	except UploadImg.DoesNotExist:
		raise Http404("Image does not exist")

	return render(request, 'img_detail.html', {"img": img})


def login_view(request):
	return render(request, 'login.html')


@require_POST
def login_check(request):
	"""登陆校验
	"""
	username = request.POST.get('username')
	password = request.POST.get('password')
	remember = request.POST.get('remember')

	if not all([username, password, remember]):
		return JsonResponse({'flag':0})

	try:
		client = Client.objects.get(username=username)
		# print(client.username)
		salt = client.salt
		# 需要获取bcrypt加密后的密码
		old_password = client.password.encode('utf-8')

		b_password = get_bcrypt(password.encode('utf-8'), salt)
		# print('bcrypt加密 %s'%b_password)

		if old_password == b_password:
			Json = JsonResponse({'flag':1})

			request.session['islogin'] = True
			request.session['username'] = username
			request.session['user_id'] = client.id

			if remember == 'true':
				# 记住用户名
				Json.set_cookie('username', username, max_age=7*24*3600)
			else:
				# 不记住用户名/若原来记住后又取消，则删除原来cookie中的该用户名
				Json.delete_cookie('username')
			return Json
		else:
			# 用户名或密码错误
			return JsonResponse({'flag':2})
	except:
		# 匹配不到正确的用户名仍视为用户名错误
		return JsonResponse({'flag':3})


# /verify_code/
def verify_code(request):
	"""生成验证码
	"""
	import random
	# 定义变量，用于画面的背景色、宽、高
	bgcolor = (random.randrange(20, 200), random.randrange(
		20, 100), 255)
	width = 100
	height = 30
	# 创建画面对象
	im = Image.new('RGB', (width, height), bgcolor)
	# 创建画笔对象
	draw = ImageDraw.Draw(im)
	# 调用画笔的point()函数绘制噪点
	for i in range(0, 100):
		xy = (random.randrange(0, width), random.randrange(0, height))
		fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
		draw.point(xy, fill=fill)
	# 定义验证码的备选值
	str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
	# 随机选取4个值作为验证码
	rand_str = ''
	for i in range(0, 4):
		rand_str += str1[random.randrange(0, len(str1))]
	# 构造字体对象，ubuntu的字体路径为“/usr/share/fonts/truetype/freefont”
	font = ImageFont.truetype('FreeMono.ttf', 23)
	# 构造字体颜色
	fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
	# 绘制4个字
	draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
	draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
	draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
	draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
	# 释放画笔
	del draw
	# 存入session，用于做进一步验证
	request.session['verifycode'] = rand_str
	# 内存文件操作
	buf = BytesIO()
	# 将图片保存在内存中，文件类型为png
	im.save(buf, 'png')
	# 将内存中的图片数据返回给客户端，MIME类型为图片png
	return HttpResponse(buf.getvalue(), 'image/png')


@login_required
def logout_view(request):
	request.session.flush()
	return redirect(reverse('gallery:index'))


def register(request):
	return render(request, 'register.html')


@require_POST
def register_handle(request):
	"""注册用户
	"""
	username = request.POST.get('username')
	password_1 = request.POST.get('password1')
	password_2 = request.POST.get('password2')
	# strip()去掉首尾空格
	phone = request.POST.get('phone').strip()
	vcode = request.POST.get('vcode')
	vcode2 = request.session['verifycode']

	phone_len = len(phone)

	if not all([username, password_1, password_2, phone, vcode]):
		return render(request, 'register.html', {'errmsg':'请输入完整信息'})

	if password_1 == password_2:
		# 如果两次密码相同
		if phone_len == 11:
			if vcode == vcode2:
				b_password, salt = get_bcrypt(password_1.encode('utf-8'))
				obj = Client.objects.add_one(username, b_password, phone, salt)
			else:
				return render(request, 'register.html', {'errmsg':'验证码错误'})
		else:
			return render(request, 'register.html', {'errmsg_phone':'手机号输入非法'})
	else:
		# 两次密码不同
		return render(request, 'register.html', {'errmsg':'两次密码不相同'}) 
	
	return redirect(reverse('gallery:index'))


def username_check(request):
	"""检验用户名是否存在
	"""
	name = request.GET.get('username')
	users = Client.objects.all()

	user_list = []
	for one in users:
		user_list.append(one.username)
		print(one.username)
	if name in user_list:
		return JsonResponse({'flag':0})
	else:
		return JsonResponse({'flag':1})


@login_required
def resetpwd(request):
	return render(request, 'change_pwd.html')


@login_required
def resetpwd_handle(request):
	username = request.session['username']

	password = request.POST.get('old_pwd')
	password_n1 = request.POST.get('new_pwd_1')
	password_n2 = request.POST.get('new_pwd_2')

	if not all([password, password_n1, password_n2]):
		return JsonResponse({'flag':0})

	try:
		client = Client.objects.get(username=username)
		salt = client.salt
		# 需要获取bcrypt加密后的密码
		old_password = client.password.encode('utf-8')
		b_password = get_bcrypt(password.encode('utf-8'), salt)

		if b_password == old_password:
			if password_n1 == password_n2:
				new_password, salt = get_bcrypt(password_n1.encode('utf-8'))
				# 更新用户的password, salt
				obj = Client.objects.update_one(username, new_password, salt)
				return JsonResponse({'flag':4})
			else:
				# 新输入的两次密码不相同
				return JsonResponse({'flag':2})
		else:
			# 密码错误
			return JsonResponse({'flag':1})
	except:
		# 未查寻到用户信息
		return JsonResponse({'flag':3})


@login_required
def comment(request, gallery_id):
	"""创建评论
	"""
	user_id = request.session['user_id']
	vcode = request.POST.get('vld_code')
	vcode2 = request.session['verifycode']
	content = request.POST.get('content')

	if request.method == "POST" and all([user_id,vcode,vcode2,content]):
		if len(content) < 5:
			# 限制内容长度，此处可从前端做判断。
			return HttpResponse(
				'评论内容太短。(3秒后自动跳转)<script type="text/javascript">'\
				'setTimeout(function(){{history.go(-1)}},3000)'\
				'</script>'.format(gallery_id))
		one = Comment.objects.add_one(author=user_id, gallery_id=gallery_id, content=content)

	return HttpResponseRedirect("/gallery_{}/#comment_head".format(gallery_id))

gallery/templates/base.html
<!DOCTYPE html>
<html lang="zh">
{% block header %}
{% include "header.html" %}
{% endblock %}


<!--<div class="jiathis_style" style="position: absolute; z-index: 1000000000; display: none; top: 50%; left: 50%; overflow: auto;"></div>
<div class="jiathis_style" style="position: absolute; z-index: 1000000000; display: none; overflow: auto;"></div>
-->
{% include "nav.html" %}

{% block content %}
{% endblock %}

{% include "footer.html" %}
</html>

gallery/templates/comment.html
<hr class="featurette-divider" id="comment_head">
<div id="id_desc_block" class="blog-post">
	<h3>评论</h3>
	{% for comment in comments %}
	<div class="row">
		<div class="col-xs-1 text-center" style="padding-top:5px;">
			<img src="/static/img/defavatar.jpg" class="img-responsive img-circle">{{ comment.author.username }}
		</div>
		<div class="col-xs-11">
			<div class="panel panel-default">
				<div class="panel-heading small text-muted" style="padding:5px;">{{ comment.create_at | date:"Y-m-d H:i:s" }}</div>
				<div class="panel-body">
					<pre>{{ comment.content }}</pre>
				</div>
			</div>
		</div><!-- COL-XS -->
	</div>
	{% endfor %}
</div>

gallery/templates/gallery.html
{% extends "base.html" %}
{% load img_extras %}

{% block header %}
{% include "header.html" with title="首页" %}
{% endblock %}

{% block content %}
<script type="text/javascript">
	
</script>


<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
<div class="blog-post row">
	<div class="col-xs-4 col-sm-3">
		<a href="{{ gallery|gallery_url }}"><img src="{{ gallery | cover_img | img_thumb_url }}" class="img-responsive img-rounded"></a>
	</div>
	<div class="col-xs-8 col-sm-9">
		<h3>
			<a href="{{ gallery|gallery_url }}">{{ gallery.title }}</a>
		</h3>
		<p class="text-muted small">
			上传者：<a href="#">{{ gallery.owner }}</a>

			<br>创建：{{ gallery.create_at }}，修改：{{ gallery.modify_at }}
		</p>
		<p class="text-muted small">
			分类：
			{% for one in gallery.category.all %}
				<a href="/?sev={{ one.id }}">{{ one.name }}</a>
			{% endfor %}
		</p>
	</div>
</div>

<div class="blog-post">
	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="#">内容</a></li>
	</ul>
</div>


<div class="blog-post row">
	{% for img in gallery.uploadimg_set.all %}
	<div class="col-xs-6 col-md-2 myClass">
		<a href="{{ img|img_detail_url }}" class="thumbnail" target="_blank">
			<img src="{{ img|img_thumb_url }}" alt="{{ img.title }}" title="{{ img.title }}">
		</a>
	</div>
	{% endfor %}
</div>

<div class="blog-post">

</div>

{% include 'comment.html' %}

<div class="blog-post">
	<div class="panel panel-default">
		<div class="panel-heading">添加评论</div>
		<div class="panel-body">
			<form action="/comment/{{ gallery.id }}/" method="POST">
				{% csrf_token %}
				<div class="form-group">
					<div class="input-group">
						{% if request.session.islogin %}
						<!-- 验证码部分 -->
							<div class="input-group-btn" style="width: 100px; height: 30px; margin: 0px;">
								<img src="/verify_code/" id="change" onclick="this.setAttribute('src','/verify_code/?verify_code='+Math.random())" style="border-radius: 4px;">
							</div>
							<div style="width: auto;margin-left:auto">
								<input class="form-control" id="id_vld_code" name="vld_code" placeholder="输入图片验证码，点击图片更换" maxlength="12" required="required" type="text" style="border-radius: 4px">
							</div>
								<input id="id_vld_hash" name="vld_hash" value="" type="hidden">
								<span class="input-group-addon" id="id_vld_code_hint"><span class="glyphicon glyphicon-asterisk"></span></span>
							</div>
						{% else %}
							<span class="input-group-btn">
								<a type="button" class="btn btn-primary" href="/login/">请先登录</a>
							</span>
							<div style="width: auto;margin-left:auto">
								<input class="form-control" id="id_vld_code" name="vld_code" placeholder="想对我说点啥就点击左侧登陆哦" maxlength="12" required="required" type="text" disabled="disabled">
							</div>
							<input id="id_vld_hash" name="vld_hash" value="" type="hidden">
							<span class="input-group-addon" id="id_vld_code_hint"><span class="glyphicon glyphicon-asterisk"></span></span>
					</div>
						{% endif %}
	
				</div>
				{% if request.session.islogin %}
				<!-- 评论框部分 -->
					<div class="form-group">
						<input name="name" value="comment_post" type="hidden">
						<textarea class="form-control" id="id_content" name="content" cols="40" rows="6"></textarea>		
					</div>
					
					<div class="form-group">
						<input id="id_btn_comment_post" class="btn btn-primary" name="submit" value="发表评论" type="submit">
					</div>
					<span class="error_4" style="color: red;position:absolute;">{{errmsg}}</span>
				{%  else%}
					<div class="form-group">
						<input name="name" value="comment_post" type="hidden">
						<textarea class="form-control" id="id_content" name="content" cols="40" rows="6" disabled="disabled"></textarea>		
					</div>
					
					<div class="form-group">
						<input id="id_btn_comment_post" class="btn btn-primary" name="submit" value="发表评论" type="submit"  disabled="disabled">
					</div>
					<span class="error_4" style="color: red;position:absolute;">{{errmsg}}</span>
				{% endif %}
			</form>
		</div>
	</div>
</div>

		</div>		
{% include "sidebar_detail.html" %}
	</div>
</div> <!-- /container -->
{% include "pager.html" %}
{% endblock %}

gallery/templates/index.html
{% extends "base.html" %}
{% load img_extras %}

{% block header %}
{% include "header.html" with title="首页" %}
{% endblock %}

{% block content %}

<script src="/static/js/index.js"></script>


<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">

<table class="table table-hover table-condensed table-bordered table-condition hidden-xs" id="category">
	<tbody>
	{% for hc in high_cates %}
		<tr>
		<th>{{ hc }}</th>
		<td>
			{% for cate in hc.category_set.all %}
			<a class="btn btn-default btn-xs" href="/?sev={{ cate.id }}">{{ cate.name }}</a>
			{% endfor %}
		</td>
	</tr>
	{% endfor %}
</tbody></table>

<div class="blog-post">
	<div class="input-group">
		<input class="form-control" id="id_search_input" onclick="this.select();" type="text" placeholder="请输入关键字,以空格分割" >
		<span class="input-group-btn">
			<button class="btn btn-primary" onclick="search_work()">搜索({{ cur_page.paginator.count }})</button>
		</span>
	</div>
</div>



<div class="row">
	{% for gallery in cur_page %}
	<div class="col-sm-3 col-xs-6">
		<div class="thumbnail">
			<a href="{{ gallery|gallery_url }}"><img src="{{ gallery | cover_img | img_thumb_url }}"></a>
			<div class="caption">
				<h5 class="text-overflow">{{ gallery.title }}</h5>
				<p class="text-warning small">
				{% for cate in gallery.category.all %}
				<span class="label label-default">{{ cate.name }}</span>
				{% endfor %}
				</p>
			</div>
		</div>
	</div>
	{% endfor %}
</div>


{% include "pager.html" %}


			<!--<hr class="featurette-divider">-->
		</div>
{% include "sidebar.html" %}
	</div>
</div> <!-- /container -->


{% endblock %}

gallery/templates/register.html
{% extends "base.html" %}
{% load img_extras %}

{% block header %}
{% include "header.html" with title="首页" %}
{% endblock %}


{% block content %}

<script type="text/javascript">
	$(function(){
		$('#change').click(function(){
			$.ajax({
				url:'/verify_code/'
				type:'POST'
			}).success(function(data){
		
			})
		})			
	})
</script>

<div class="container">
	<div class="row row-offcanvas row-offcanvas-right">
		<div class="col-xs-12 col-sm-9">
			
<div class="blog-post">
	<ul class="nav nav-tabs">
		{% if request.session.islogin %}
			<li role="presentation" class="active"><a href="/register/">新帐户注册</a></li>
			<li role="presentation"><a href="/resetpwd/" class="active">重设密码</a></li>
		{% else %}
			<li role="presentation">
				<a href="/login/">账号登录</a>
			</li>
			<li role="presentation" class="active"><a href="/register/">新帐户注册</a></li>
			<li role="presentation"><a href="/resetpwd/">重设密码</a></li>
		{% endif %}
	</ul>
	<br>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<form action="/register_handle/" method="post">
			{% csrf_token %}
			<div class="form-group">
				<label>用户名（只能使用英文或者英文+数字，不可使用中文）：</label>
				<div class="input-group">
					<input class="form-control" id="id_username" name="username" maxlength="30" placeholder="至少6位字符的用户名，不可以是纯数字" required="required" type="text">
					<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
				</div>
				<div id="id_username_hint" style="display:none;color: red;position:absolute;"></div>
			</div>

			<div class="form-group">
				<label>输入密码：</label>
				<div class="input-group">
					<input class="form-control" id="id_password1" name="password1" placeholder="请设置登录密码" required="required" type="password">
					<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
				</div>		
			</div>

			<div class="form-group">
				<label>再输入一遍密码：</label>
				<div class="input-group">
					<input class="form-control" id="id_password2" name="password2" value="" placeholder="再输入一遍，以确认密码输入正确无误" required="required" type="password">
					<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
				</div>	
			</div>

			<div class="form-group">
				<label>手机号码：</label>
				<div class="input-group">
					<input class="form-control" id="id_phone" name="phone" placeholder="11位数字的手机号码" required="required" type="text">
					<!-- <span class="input-group-btn"><button type="button" class="btn btn-default" id="id_btn_sms">发送短信验证码</button></span> -->
					<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
				</div>
				<div id="id_phone_hint" style="color: red;position:absolute;">{{ errmsg_phone }}</div>
			</div>

			<div class="form-group">
				<!-- 验证码 -->
				<img src="/verify_code/" id="change" onclick="this.setAttribute('src','/verify_code/?verify_code='+Math.random())" style="border-radius: 4px">
				<input class="verify_code" id="verify" type="text" name="vcode" required="required" placeholder="点击图片更换验证码" /><br/>
			</div>

			<!-- <div class="form-group">
				<label>短信验证码：</label>
				<div class="input-group">
					<input class="form-control" id="id_vfy_code" maxlength="12" name="vfy_code" placeholder="手机接收到的短信验证码（4位数字）" required="required" type="text">
					<input id="id_vfy_hash" name="vfy_hash" value="n/a" type="hidden">
					<span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
				</div>	
			</div>	 -->		

			<div class="form-group">
				<input name="submit" id="id_btn_submit" value="注 册" class="btn btn-primary form-control" type="submit">
				<div id="id_last_hint" style="color: red;position:absolute;">{{errmsg}}</div>
			</div>	
		</form>
	</div>
</div>


		</div>
{% include "sidebar.html" %}
	</div>
</div> <!-- /container -->


<script src="/static/js/register.js"></script>

{% endblock %}